language: java
jdk: oraclejdk11

script: mvn -e verify

after_success:
  - bash <(curl -s https://codecov.io/bash)
motifications:
  email:
    recipients:
      - dilkar2009@yandex.ru
      on_failure: always
      on_succes: change

